version: "3.9"
services:
  database:
    container_name: prisma_database
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    ports:
      - "1438:1433"
    environment:
      SA_PASSWORD: yourStrong(!)Password
      ACCEPT_EULA: Y
  api:
    container_name: prisma_api
    build:
      context: .
      target: dev
    restart: always
    volumes:
      - .:/usr/src/app
    ports:
      - "3002:3000"
      - "5556:5555"
    depends_on:
      - database